from pygame import image

img_empty_field = image.load("img/empty.png")
img_flag = image.load("img/flag.png")
img_element = image.load("img/Grid.png")
img_element1 = image.load("img/grid1.png")
img_element2 = image.load("img/grid2.png")
img_element3 = image.load("img/grid3.png")
img_element4 = image.load("img/grid4.png")
img_element5 = image.load("img/grid5.png")
img_element6 = image.load("img/grid6.png")
img_element7 = image.load("img/grid7.png")
img_element8 = image.load("img/grid8.png")
img_mine = image.load("img/mine.png")
img_mineClicked = image.load("img/mineClicked.png")
img_mineFalse = image.load("img/mineFalse.png")
